### ISSUE TITLE
A issue in Perform simulation module happened in Colab, seems caused by parallel threads.

### ISSUE THREAD

**Issue by PSGLGDnoChampion** [tymoteuszb/implicit-slam#2]
Unable to run in Colab. The error happened at
mappingThread = MappingThread(sharedData)

ValueError: tf.function only supports singleton tf. Variables created on the first cal1. Make sure the tf.Variable is onlycreated once or created outside tf.function.See https:/ww.tensorflow.org/guide/function#creating_tfvariables for more information.

**Comment by tym-b** [comment]
Hi! Thanks for reporting this.

I think that you might have come across the problem I noted in **Perform simulation** cell. When you call a `tf.function` with an instance of `tf.Variable` (passed as an argument or initialised within the function), you need to stick to this very instance of `tf.Variable` in the subsequent calls. Therefore, in order to rerun the simulation you need to make sure the mapping and tracking threads are finished (the code under `# Kill previously running threads` should do the job) and rerun all cells starting from **Define shared data structure**.

I've been thinking how to solve this problem in elegant way. One idea was to reuse the `tf.Variables`, however I haven't found a straightforward way to reset the `tf.Variables` of optimisers.

**Comment by PSGLGDnoChampion** [comment]
Thanks for your reply very much. 
I didn't  modify your codes in Colab, but I cannot directly use "run all" in the Colab because of the above error, so how should I run? Thanks again.

**Comment by tym-b** [comment]
Hi,

Maybe one of the threads is still running when you're attempting to rerun all. You could try running this snippet before hitting `Run all`:

```
try:
    sharedData.run_mapping = False
    sharedData.run_tracking = False
    mappingThread.join()
    trackingThread.join()
except:
    pass
```
